### PR TITLE
Update variables problem definition

### PR DESCRIPTION
**Pull request by davecocoa**
The solution uses `#000` which seems reasonable so can we update the problem to match?

Thanks for putting this together!

### CODE REVIEW

**Comment by claudiopro** [comment]
Thanks Dave, it's good feedback. Sass always tries to be concise so `#000000` is transformed to `#000`, which appears be in the output of the execution of submission and solution when they are compared. I agree we should keep solution and instructions in sync. I wonder though if we shouldn't be friendly to Node developers not proficient with CSS (which [NodeSchool](http://nodeschool.io) targets), or assume a basic proficiency with CSS? I'm fine with both TBH.

**Comment by davecocoa** [comment]
Oh, I didn't realise Sass should be transforming it. Then I'm confused about why I got this:

learn-sass-err

It's definitely running through sass, because it used the variable, I'm not sure why it isn't shortening it...

**Comment by claudiopro** [comment]
Interesting, let me troubleshoot it...

**Comment by davecocoa** [comment]
My `style.scss` file:

```
$colour: #000000;

body {
  color: $colour;
}
```

**Comment by claudiopro** [comment]
Scratch that, it is [new behavior in Sass 3.4](http://stackoverflow.com/questions/15757665/why-does-sass-change-the-format-of-my-colors) =___="

> The only change from 3.3 to 3.4 is that when using variables, Sass will preserve the format of your color... unless it is in something other than the keyword, hex, or rgba formats.

**Comment by claudiopro** [comment]
Thanks, all set!

**Comment by davecocoa** [comment]
Nice! Cool to see the logic behind the behaviour =)

**Pull request merged**
